<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Elke Michlmayr">

<title>Life cycle impact assessment for a district heating project with seasonal storage</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b4406b7675125bc2ba204020e191172.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-be9206a58a27969b3ea3001da8f26fef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Life cycle impact assessment for a district heating project with seasonal storage</h1>
<p class="subtitle lead">A case study analysis for a community project based in Bracht, Rauschenberg, Hessen, Germany</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Elke Michlmayr </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>A life cycle impact assessment (LCIA) was conducted for a solar district heating community project under construction in Bracht, Germany. It incorporates solar thermal collectors, a seasonal heat storage unit powered through an included electric heat pump, a supplemental biomass boiler as a backup solution for when there is no heat available from the solar based system, and a district heating network to supply residential consumers.</p>
<p>The assessment used standard environmental impact methods such as the Ecological Scarcity method to evaluate the system over a 50-year lifetime. Despite supplying the majority of the energy, the solar thermal component with seasonal storage contributed less than 30% to the overall environmental impact. The supplemental biomass and the required electricity sourced from the grid accounted for roughly two-thirds of the total impact, even though they provided only one-third of the energy.</p>
<p>The results are encouraging and show that the Bracht system is environmentally favorable compared to many alternatives. However, substantial potential for improvement through optimization of the system’s operating conditions remains. The key opportunities include using renewable electric energy for the heat pump, and reducing heat losses in storage and district heating network to minimize, or even completely eliminate, the need for supplemental biomass. This is achievable by optimizing settings such as the system’s operating temperature.</p>
</section>
<section id="introduction-and-related-work" class="level1">
<h1>Introduction and related work</h1>
<p>Heating is a key contributor to energy consumption, accounting for roughly half of all energy used in the EU, with 60% of that energy still generated from fossil fuels <span class="citation" data-cites="euroheat2023">Euroheat &amp; Power (<a href="#ref-euroheat2023" role="doc-biblioref">2023</a>)</span>. District heating is a system in which a central heating plant supplies heat to multiple households through a network of pipes. It works in two main ways, either by utilizing surplus heat from sources such as waste incineration plants to provide heating for residential areas and service centers <span class="citation" data-cites="sfoe2020">Swiss Federal Office of Energy (<a href="#ref-sfoe2020" role="doc-biblioref">2020</a>)</span>, or by relying on dedicated energy sources such as biomass or solar thermal collectors. There are approximately 6,000 district heating systems operating across the EU <span class="citation" data-cites="euroheat2023">Euroheat &amp; Power (<a href="#ref-euroheat2023" role="doc-biblioref">2023</a>)</span>. Process heating uses a similar setup but is designed for industrial applications, which typically require higher temperatures. Studies such as <span class="citation" data-cites="jeandaux2021life">Jeandaux et al. (<a href="#ref-jeandaux2021life" role="doc-biblioref">2021</a>)</span> have shown that using a centralized heating system with a heat distribution network results in a lower environmental impact compared to standalone heating units installed at each consumer’s site.</p>
<p>Solar thermal collectors (STCs) are devices that absorb solar radiation and convert it into heat. There are several types of STCs, including flat plate collectors, unglazed water collectors, and evacuated tube collectors. These systems are often combined with heat pumps to bridge the temperature gap between the water produced by the solar field and the temperature required by the district heating delivery system <span class="citation" data-cites="wikipedia2020">Wikipedia (<a href="#ref-wikipedia2020" role="doc-biblioref">2025</a>)</span>. According to <span class="citation" data-cites="iea2024">Weiss and Spörk-Dür (<a href="#ref-iea2024" role="doc-biblioref">2024</a>)</span>, there are more than 300 large-scale district heating systems worldwide powered by STCs, and over 1.200 STC systems that provide industrial process heat.</p>
<p>Solar thermal collectors are a mature technology. In 2023, the total operational solar thermal capacity reached 560 GWth, covering roughly 800 km² of collector area <span class="citation" data-cites="iea2024">Weiss and Spörk-Dür (<a href="#ref-iea2024" role="doc-biblioref">2024</a>)</span>. STC-provided capacity varies seasonally depending on available sunlight. In some cases, STCs are used only during certain parts of the year, for example to allow a biomass-powered plant to shut down during summer when it would otherwise operate at extremely low capacity.</p>
<p>STCs can be combined with short-term heat storage that acts as a buffer, or with seasonal heat storage tanks, sometimes referred to as pit thermal energy storage (PTES). These include underground hot water basins that store excess heat from the warm season for use in the cold season. However, this setup involves heat losses.</p>
<p>If space limitations or land costs require it, STCs can be installed at a distance from consumers and heat plants, with pipelines connecting them. An example is Priština, where the distance is around 4 km <span class="citation" data-cites="euroheat2023">Euroheat &amp; Power (<a href="#ref-euroheat2023" role="doc-biblioref">2023</a>)</span>. This introduces a trade-off, as the remote location requires laying additional underground piping.</p>
<p>In scientific literature, only a small number of LCIA case studies for district heating systems exist, such as those for the systems in Milan <span class="citation" data-cites="famiglietti2021environmental">Famiglietti et al. (<a href="#ref-famiglietti2021environmental" role="doc-biblioref">2021</a>)</span> and Marseille <span class="citation" data-cites="vauchez2023life">Vauchez et al. (<a href="#ref-vauchez2023life" role="doc-biblioref">2023</a>)</span>. Life cycle impact assessment, particularly based on the ReCiPe method, has been used to evaluate the environmental impact of different STC-powered district heating configurations in <span class="citation" data-cites="abokersh2020framework">Abokersh et al. (<a href="#ref-abokersh2020framework" role="doc-biblioref">2020</a>)</span>. The findings indicate that larger systems serving many households tend to have a lower environmental impact per unit of energy delivered. In <span class="citation" data-cites="solano2023life">Solano et al. (<a href="#ref-solano2023life" role="doc-biblioref">2023</a>)</span>, the authors present an LCIA study of a STC plant connected to the Geneva district heating network.</p>
<p>For the community district heating project in Bracht, the economic viability in comparison to conventional energetic renovation measures has been assessed in a previous study <span class="citation" data-cites="kelch2024comparison">Kelch et al. (<a href="#ref-kelch2024comparison" role="doc-biblioref">2024</a>)</span>. However, the environmental impact of the project has not yet been examined in detail. This gap forms the focus of the present study.</p>
</section>
<section id="sec-metho" class="level1">
<h1>Methodology and research questions</h1>
<p>The LCIA was performed using the SimaPro 9.6.0.1 software <span class="citation" data-cites="SimaPro2024">PRé Sustainability (<a href="#ref-SimaPro2024" role="doc-biblioref">2024</a>)</span>. The foreground data was collected from various online sources and combined with background data from the Ecoinvent v3 database <span class="citation" data-cites="wernet2016ecoinvent">Wernet et al. (<a href="#ref-wernet2016ecoinvent" role="doc-biblioref">2016</a>)</span> and the UVEK LCI database version DQRv2:2025 <span class="citation" data-cites="FOEN2025">Federal Office for the Environment (FOEN) (<a href="#ref-FOEN2025" role="doc-biblioref">2025</a>)</span>. The environmental impacts were assessed using the mid-point level Environmental Footprint (EF) method <span class="citation" data-cites="ec2021EF">European Commission (<a href="#ref-ec2021EF" role="doc-biblioref">2021</a>)</span>, the Ecological Scarcity 2021 (v1.04) method <span class="citation" data-cites="FOEN2021">Federal Office for the Environment (FOEN) (<a href="#ref-FOEN2021" role="doc-biblioref">2021</a>)</span> at the single score level with UVEK LCI weighting set, and the IPCC 2021 GWP100 methodology <span class="citation" data-cites="IPCC_2021_WGI_Annex_III">Dentener et al. (<a href="#ref-IPCC_2021_WGI_Annex_III" role="doc-biblioref">2021</a>)</span>.</p>
<p>The research questions were formulated as follows:</p>
<ol type="1">
<li>What is the relevance of the additional electricity required in the setup and the supplemental biomass boiler with respect to the overall environmental impact? The hypothesis is that the additional electricity and biomass required will amount to a sizable part of the overall environmental impact.</li>
<li>How does the STC based system with seasonal heat storage compare to other heating technologies in terms of environmental impact? The comparison will include district heating from other sources that would be available in small communities (such as a heat pump or wood chips), and consumer side heating installations such as oil or gas boilers. The hypothesis is that the STC based system will have a lower environmental impact compared to other district heating setups and to fossil energy based consumer installations.</li>
<li>What is the environmental impact contribution of the seasonal heat storage unit in the production, construction, and use stages in the life cycle? A sensitivity analysis will be performed to assess the benefits of the STC based system with a seasonal heat storage component included under several assumed loss coefficients for the storage component and the district heating pipe system. The hypothesis is that the seasonal storage component will lower the environmental impact.</li>
</ol>
<p>The following chapters will cover all the necessary stages of the LCIA: goal and scope definition in <a href="#sec-goal" class="quarto-xref">Section&nbsp;4</a>, inventory analysis in <a href="#sec-lci-overview" class="quarto-xref">Section&nbsp;5</a>, impact assessment in <a href="#sec-results" class="quarto-xref">Section&nbsp;6</a>, and interpretation in <a href="#sec-inter" class="quarto-xref">Section&nbsp;7</a>.</p>
</section>
<section id="sec-goal" class="level1">
<h1>Goal and scope</h1>
<p>The goal and scope definition is a fundamental step in any life cycle impact assessment (LCIA), as it provides a clear description of the product system under study, its system boundaries, and the definition of a functional unit that reflects the output of the system in a consistent and measurable way.</p>
<div id="fig-bracht-overview" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bracht-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/bracht_overview.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bracht-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: System overview for the Bracht community district heating network.
</figcaption>
</figure>
</div>
<p>For the present LCIA, the specific goals are to address the research questions outlined in <a href="#sec-metho" class="quarto-xref">Section&nbsp;3</a>. The scope of the assessment encompasses a district heating project initiated and operated by a cooperative composed of future household consumers and the local municipal council. As illustrated in <a href="#fig-bracht-overview" class="quarto-xref">Figure&nbsp;1</a>, the system includes the following key components:</p>
<ul>
<li>solar thermal collector (STC) field,</li>
<li>seasonal storage unit (SSU),</li>
<li>heat pump component powered with electricity from the grid with buffer storage unit,</li>
<li>biomass combustion unit serving backup heat when stored heat is unavailable,</li>
<li>facility to house the heat pump and the biomass combustion unit,</li>
<li>district heating distribution network that supplies to residential consumers,</li>
<li>and receiver units installed in each participating household.</li>
</ul>
<p>The lifetime of the district heating system is assumed to be 50 years. There are at least 180 consumer households expected, which is roughly 60% of all households that exist in the local community. The plant is currently under construction and on track to be operational for the 2025 winter heating period.</p>
<p>The system diagram shown in <a href="#fig-system-diagram" class="quarto-xref">Figure&nbsp;2</a> describes the product system and its boundaries. The functional unit is defined to be 1 MegaJoule (MJ) of thermal energy provided to the consumer directly at the consumer site during the heating period. Using MJ instead of kilowatt-hours of thermal energy (kWh<sub>th</sub>) ensures consistency with the UVEK processes for other forms of district heating in SimaPro that the comparison will be performed against.</p>
<div id="fig-system-diagram" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-border="true">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-system-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/system_diagram.png" class="img-fluid figure-img" style="width:80.0%" data-fig-border="true">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-system-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: System diagram for the Bracht community district heating network.
</figcaption>
</figure>
</div>
</section>
<section id="sec-lci-overview" class="level1">
<h1>Life cycle inventory (LCI)</h1>
<p>This section outlines the foundational data used to support system modelling. Extensive project-related information for the Bracht community district heating system is available on the project website <span class="citation" data-cites="bracht2025">City of Rauschenberg (<a href="#ref-bracht2025" role="doc-biblioref">2025c</a>)</span>. This was used as a key source for detailed LCI data. It provided detailed data on the solar thermal collector field, the seasonal storage unit, and heat preparation systems comprising the heat pump, buffer storage, installation facility, and consumer installations.</p>
<p>The comparison datasets and the district heating network were modelled based on UVEK LCI data <span class="citation" data-cites="FOEN2025">Federal Office for the Environment (FOEN) (<a href="#ref-FOEN2025" role="doc-biblioref">2025</a>)</span>, an existing resource for conducting LCIAs of energy systems and infrastructure within Switzerland and the broader European context provided by the Swiss Federal Office of Energy (abbreviated in English as SFOE, and in German as UVEK). For electricity input, the modelling assumed the European Network of Transmission System Operators for Electricity (ENTSO-E) production mix, also provided in the UVEK dataset, to ensure the model reflects conditions typical of a plant operating within the European region.</p>
<p>Additional LCI details for all components are provided in <a href="#sec-lci" class="quarto-xref">Section&nbsp;9.1</a>. Detailed specifications and parameters of the resulting system model are described in <a href="#sec-sima" class="quarto-xref">Section&nbsp;9.2.1</a>. The remainder of this section outlines the key assumptions regarding component lifetimes, expected electricity demand, and thermal loss coefficients.</p>
<section id="component-lifetimes" class="level2">
<h2 class="anchored" data-anchor-id="component-lifetimes">Component lifetimes</h2>
<p>The planned lifetime for the Bracht plant is 50 years. The assumed individual component lifetimes and the resulting relevant multipliers are shown in <a href="#tbl-component-lifetimes" class="quarto-xref">Table&nbsp;1</a>. The assumed individual component lifetimes are in line with the assumptions used in <span class="citation" data-cites="bracht2022">Kelch et al. (<a href="#ref-bracht2022" role="doc-biblioref">2022</a>)</span>.</p>
<div id="tbl-component-lifetimes" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Assumed component lifetimes">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-component-lifetimes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-component-lifetimes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Years</th>
<th>Multiplier</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Solar thermal collectors</td>
<td>30</td>
<td>1.67</td>
<td><span class="citation" data-cites="grosse2017long">(<a href="#ref-grosse2017long" role="doc-biblioref">Große et al., 2017</a>)</span></td>
</tr>
<tr class="even">
<td>Seasonal storage unit</td>
<td>30</td>
<td>1.67</td>
<td><span class="citation" data-cites="bracht2022">(<a href="#ref-bracht2022" role="doc-biblioref">Kelch et al., 2022</a>)</span></td>
</tr>
<tr class="odd">
<td>Heat pumps</td>
<td>20</td>
<td>2.5</td>
<td><span class="citation" data-cites="wolf2017integration">(<a href="#ref-wolf2017integration" role="doc-biblioref">Wolf, 2017</a>)</span></td>
</tr>
<tr class="even">
<td>Heat buffer storage</td>
<td>20</td>
<td>2.5</td>
<td><span class="citation" data-cites="grosse2017long">(<a href="#ref-grosse2017long" role="doc-biblioref">Große et al., 2017</a>)</span></td>
</tr>
<tr class="odd">
<td>Heat installation facility</td>
<td>50</td>
<td>1</td>
<td><span class="citation" data-cites="vdi2012vdi">(<a href="#ref-vdi2012vdi" role="doc-biblioref">VDI, 2012</a>)</span></td>
</tr>
<tr class="even">
<td>Heat exchange stations at consumer</td>
<td>20</td>
<td>2.5</td>
<td><span class="citation" data-cites="bracht2022">(<a href="#ref-bracht2022" role="doc-biblioref">Kelch et al., 2022</a>)</span></td>
</tr>
<tr class="odd">
<td>District heating network</td>
<td>50</td>
<td>1</td>
<td><span class="citation" data-cites="bracht2022">(<a href="#ref-bracht2022" role="doc-biblioref">Kelch et al., 2022</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-loss-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="sec-loss-coefficients">Electrical power requirements and loss coefficient assumptions</h2>
<p>Performance data from <span class="citation" data-cites="tuev2021">TÜV Rheinland (<a href="#ref-tuev2021" role="doc-biblioref">2021</a>)</span> provides several estimates of the annual output for the solar thermal collectors used in this project. These estimates vary by geographic location and desired output temperature. The most geographically relevant data point is for Würzburg, with an output of 5.283 kWh per collector per year at a target output temperature of 75 degrees Celsius (°C). Given a total of 855 collectors, the estimated gross thermal energy production is approximately 4.517 MWh per year.</p>
<p>According to the project documentation <span class="citation" data-cites="bracht2025faq">City of Rauschenberg (<a href="#ref-bracht2025faq" role="doc-biblioref">2025a</a>)</span>, 2.700 MWh per year are expected to reach end-user households. This implies a total system loss of approximately 40%, accounting for thermal losses in the storage unit and distribution piping.</p>
<p>The energy distribution for heating supply for the Bracht plant is reported in <span class="citation" data-cites="epp2024high">Epp (<a href="#ref-epp2024high" role="doc-biblioref">2024</a>)</span> as follows:</p>
<ul>
<li>67 % from stored solar thermal energy (approximately 2.258 MWh),</li>
<li>26 % from biomass sources (approximately 904 MWh), and</li>
<li>6 % from the electricity grid (approximately 209 MWh)</li>
</ul>
<p>It is noted that the distribution totals 99 instead of 100, likely due to rounding, but since this is information from the original source and the difference is small, it was adopted without modification.</p>
<p>Since detailed methods for the loss estimates used in the Bracht assumptions were not provided in the public documentation, the modelling described in this document assumes a 20% loss coefficient as the default for the heat transmission pipe network. The relevant literature and further rationale for the choice are presented in <a href="#sec-pipe-loss" class="quarto-xref">Section&nbsp;7.3.1</a>. Given this assumption, the implied thermal loss within the seasonal storage unit would be approximately 50% to align with the reported figures from <span class="citation" data-cites="bracht2025faq">City of Rauschenberg (<a href="#ref-bracht2025faq" role="doc-biblioref">2025a</a>)</span>. These assumptions were incorporated into the system model as the default values. More background and a detailed discussion of thermal loss coefficients and their influence on system performance is presented in the sensitivity analysis in <a href="#sec-sensitive-loss" class="quarto-xref">Section&nbsp;7.3</a>.</p>
</section>
</section>
<section id="sec-results" class="level1">
<h1>Results</h1>
<p>The system model, as detailed in <a href="#sec-sima" class="quarto-xref">Section&nbsp;9.2.1</a>, was implemented using SimaPro <span class="citation" data-cites="SimaPro2024">PRé Sustainability (<a href="#ref-SimaPro2024" role="doc-biblioref">2024</a>)</span>. This model served as the foundation for generating LCIA results using the Environmental Footprint (EF) method <span class="citation" data-cites="ec2021EF">European Commission (<a href="#ref-ec2021EF" role="doc-biblioref">2021</a>)</span> and the Ecological Scarcity 2021 (v1.04) method <span class="citation" data-cites="FOEN2021">Federal Office for the Environment (FOEN) (<a href="#ref-FOEN2021" role="doc-biblioref">2021</a>)</span>. The corresponding results derived from these assessments are presented in this section.</p>
<div id="fig-network-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-network-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_network_bar.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-network-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Relative environmental impact for components of Bracht community district heating system (Ecological Scarcity 2021, v1.04, UVEK LCI weighting)
</figcaption>
</figure>
</div>
<p>To address the first research question regarding the environmental impact of the additional electricity and the supplemental biomass burnt in the wood boiler, the relative influence of the individual components of the solar thermal district heating system on overall environmental impact was evaluated using the Ecological Scarcity 2021 (v1.04) method. The assessment was conducted at the single-score level, applying the UVEK LCI weighting set to define the relative importance of the different damage categories. The results are presented in <a href="#fig-network-bar" class="quarto-xref">Figure&nbsp;3</a>. They show that biomass (27.3 %) and electricity (35.8 %) have a very large impact. They are responsible for nearly two-thirds of the environmental impact of the overall system. The solar thermal based part of the system with solar thermal field, seasonal storage, and heat pump is responsible for less than 30 % of the overall environmental impact, although they supply two-thirds of the total energy production <span class="citation" data-cites="epp2024high">Epp (<a href="#ref-epp2024high" role="doc-biblioref">2024</a>)</span>. Only one-third of the energy delivered to end consumers originates from biomass and electricity.</p>
<p>For a more detailed view of the environmental impact by individual damage categories, <a href="#fig-ef-network-bar" class="quarto-xref">Figure&nbsp;4</a> presents the drilled-down individual results for the most relevant impact categories <em>Climate change</em>, <em>Particulate matter</em>, <em>Eutrophication (terrestrial)</em>, <em>Land use</em>, <em>Resource use (minerals and metals)</em>, and <em>Resource use (fossils)</em>. The figure shows that biomass combustion is the dominant contributor to land use, particulate matter, and terrestrial eutrophication. In contrast, electricity use is the primary driver of impacts for fossil resource use and climate change. The environmental impact for minerals and metals resource use is most significantly influenced by heat preparation and the solar thermal collectors. The seasonal storage unit is not dominant for any damage category, but some contributions are visible to climate change and fossil resource use. Similar effects can be seen for the solar thermal collector.</p>
<div id="fig-ef-network-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ef-network-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_ef_network_bar_faceted.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ef-network-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Relative environmental impact of Bracht community district heating network system components for the six most relevant damage categories (Environmental Footprint Method).
</figcaption>
</figure>
</div>
<p>In summary, the electricity and biomass used to operate and supplement the system are the primary contributors to the overall environmental impact. Electricity consumption is unavoidable due to the operation of the heat pump. However, its impact can potentially be mitigated by sourcing electricity from renewable sources instead of the ENTSO-E production mix (as described in <a href="#sec-lci-overview" class="quarto-xref">Section&nbsp;5</a>), an option explored in more detail in <a href="#sec-sensitive-elec" class="quarto-xref">Section&nbsp;7.2</a>. Strategies to reduce biomass consumption by improving thermal efficiency, such as lowering heat loss coefficients, are examined in <a href="#sec-sensitive-loss" class="quarto-xref">Section&nbsp;7.3</a>.</p>
<p>To address the second research question, the environmental impact of heat generated by the solar thermal collector based district heating system with seasonal heat storage was compared to that of other heating technologies. The results, presented in <a href="#fig-es-single-score" class="quarto-xref">Figure&nbsp;5</a>, show a comparison of the environmental impacts of STC-based district heating with other district heating (DH) options commonly available in small communities, such as central systems based on wood chips (biomass) or geothermal heat pumps as the energy source. Additionally, the analysis includes consumer-side heating installations (CI), such as oil and gas boilers. The assessment was conducted using the Ecological Scarcity 2021 (v1.04) method at the single-score level, applying the UVEK LCI weighting set.</p>
<!-- The results in ascending order: district heating based on wood chips 165 Pt per kWh, Bracht solar thermal based district heating 170 Pt per kWh, district heating based on geothermal heat pump 225 Pt per kWh, gas based consumer installation 281 Pt per kWh, oil based consumer installation 430 Pt per kWh. -->
<p>The results are expressed in environmental impact points (Pt) per kilowatt-hour (kWh) of heat delivered. They reveal that the heat produced by the Bracht plant with 170 Pt per kWh of heat shows the second lowest environmental impact compared to other heating technologies. The largest contributor is the <em>Global warming</em> category (which is comparable to the <em>Climate Change</em> damage category in the Environmental Footprint method). This is dominantly caused by the electricity required (ENTSO-E production mix as discussed in <a href="#sec-lci-overview" class="quarto-xref">Section&nbsp;5</a>), and to a lesser extent by the seasonal storage unit and the solar thermal collectors (cf. <a href="#fig-ef-network-bar" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div id="fig-es-single-score" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-es-single-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_es_single_score.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-es-single-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Comparison of environmental impact of Bracht community district heating network to other energy sources for district heating such as wood chips and heat pump, and to consumer installations such as gas and oil burners (Ecological Scarcity 2021 v1.04, UVEK LCI weighting).
</figcaption>
</figure>
</div>
<p>The lowest environmental impact with 165 Pt per kWh of heat is returned for the district heating system based on wood chips as the energy source, even with the impact on main air pollutants and particulate matter (PM) having a significant impact on the overall results for this setup. The district heating system based on a geothermal heat pump as the energy source has the third lowest impact with 225 Pt per kWh of heat, to the largest extent from impact on radioactive waste to deposit. Gas and oil based consumer installations fare significantly worse with 281 Pt and 430 Pt per kWh of heat, dominantly from impact on climate change.</p>
<p>As before, <a href="#fig-ef-midpoints" class="quarto-xref">Figure&nbsp;6</a> presents the individual results for the most relevant damage categories, comparing them relative to the highest value in each category, which is shown as the longest bar representing 100% relative impact. This analysis confirms the findings from <a href="#fig-es-single-score" class="quarto-xref">Figure&nbsp;5</a>, clearly demonstrating that oil and gas boilers have extremely high impacts in the <em>Climate change</em> category with 100% and 70%, respectively. Additionally, the oil and gas boilers exhibit the highest fossil resource use, at 100% and 80%. A clear trade-off exists because each heating technology performs worst in different impact categories. For example, the district heating network using wood chips shows lower climate change impacts but the highest relative impacts in <em>Terrestrial eutrophication</em>, <em>Land use</em>, and <em>Particulate matter</em> (PM). While PM impact was visible in <a href="#fig-es-single-score" class="quarto-xref">Figure&nbsp;5</a>, <em>Terrestrial eutrophication</em> and <em>Land use</em> impacts were not significant in the single score results. Similarly, solar thermal and geothermal-based district heating systems have the highest relative impacts in Minerals and metals resource use, at 100% and 83%, respectively. These trade-offs imply that selecting a heating technology depends on which environmental impacts are prioritized for a given use case. This highlights the need to weigh and balance different categories manually, or to rely on a single score method if applicable.</p>
<div id="fig-ef-midpoints" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ef-midpoints-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_ef_midpoints_faceted.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ef-midpoints-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Damage assessment for the most relevant categories using the Environmental Footprint Method, visualized as relative environmental impacts in comparison. See <a href="#fig-ef-midpoints-others" class="quarto-xref">Figure&nbsp;10</a> for the results for categories omitted in the given chart.
</figcaption>
</figure>
</div>
</section>
<section id="sec-inter" class="level1">
<h1>Interpretation and discussion</h1>
<p>This chapter discusses the results introduced in <a href="#sec-results" class="quarto-xref">Section&nbsp;6</a>. They revealed that the district heating system based on solar thermal energy and seasonal storage compares favorably to other means of heating. However, in the given modelling, with limitations as documented in <a href="#sec-model-limitation" class="quarto-xref">Section&nbsp;7.1</a>, it exhibits higher environmental impact compared to the district heating system based on wood chips as the energy source. The electricity and the supplemental biomass required were found to be the two top single contributors to the overall results. To understand the saving potential from using lower-emitting (see <a href="#sec-sensitive-elec" class="quarto-xref">Section&nbsp;7.2</a>) or less energy resources (see third research question and <a href="#sec-sensitive-loss" class="quarto-xref">Section&nbsp;7.3</a>), sensitivity analyses for source of electricity and loss coefficients for the heat loss in the seasonal storage unit and the district heating pipes were performed. The combined results from both sensitivity analyses are summarized in <a href="#sec-combined" class="quarto-xref">Section&nbsp;7.4</a>.</p>
<section id="sec-model-limitation" class="level2">
<h2 class="anchored" data-anchor-id="sec-model-limitation">Modelling limitations</h2>
<p>Data availability was generally satisfactory with one notable exception for the modelling of the heat pumps used in the system (see <a href="#sec-hp" class="quarto-xref">Section&nbsp;9.1.3</a> for specifications). There are two heat pumps with 630 kW max electrical input power each used in the system, but in the UVEK data, the largest sized heat pump available has a maximum of 50 kW power. The best possible assumption in this situation was that the two large heat pump have the same impact as 25 units of the 50 kW heat pump, but this is likely leading an overestimation of the resource use for minerals and metals. This is acceptable since with 6 %, the heat pump showed only minor impacts on the overall results (see <a href="#fig-network-bar" class="quarto-xref">Figure&nbsp;3</a>).</p>
<p>The UVEK data for the other energy sources for district heating (wood chips, heat pump) uses an 11 % assumption for district heating pipe heat loss, which means that the solar thermal data with a 20% assumption as mentioned in <a href="#sec-loss-coefficients" class="quarto-xref">Section&nbsp;5.2</a> was disadvantaged in the comparison in <a href="#fig-es-single-score" class="quarto-xref">Figure&nbsp;5</a>. The effect of these assumptions on the results will be investigated in <a href="#sec-sensitive-loss" class="quarto-xref">Section&nbsp;7.3</a>.</p>
<p>Worth mentioning is that the UVEK data for district heating has a lifetime assumption of 30 years whereas the Bracht district heating network setup assumes 50 years. This is acceptable since the district heating system showed only minor impact of 6.6 % on the overall results (see <a href="#fig-network-bar" class="quarto-xref">Figure&nbsp;3</a>).</p>
<p>There was a problem with the weights for the damage category <em>Water resources, net balance</em> in the UVEK LCI weighting set that required excluding this category from the analysis.</p>
<p>System deconstruction was modeled only for the major infrastructure components, specifically the solar thermal collector field and the seasonal storage unit. The model includes the disposal of plastic materials used for sealing and insulation in the seasonal storage unit, assuming treatment via municipal waste incineration. For the remaining system components, the deconstruction processes were included in the model, but final disposal or material recovery for these components was not considered within the scope of this analysis (cf.&nbsp;system diagram in <a href="#fig-system-diagram" class="quarto-xref">Figure&nbsp;2</a>).</p>
</section>
<section id="sec-sensitive-elec" class="level2">
<h2 class="anchored" data-anchor-id="sec-sensitive-elec">Sensitivity analysis: Source of electricity</h2>
<p>The results as presented in <a href="#fig-es-single-score" class="quarto-xref">Figure&nbsp;5</a> indicate that the dominant environmental impact arises from the electricity demand of the system, which originates from the heat pump. In the default model, the electricity mix was modeled based on the ENTSO-E production mix <span class="citation" data-cites="FOEN2025">Federal Office for the Environment (FOEN) (<a href="#ref-FOEN2025" role="doc-biblioref">2025</a>)</span>. This includes a built-in assumption that the electricity production mix will remain constant over the lifetime of the plant. In this section, the effects of the default choice for the modelling as well as potentially achievable savings by using lower-emitting electricity are assessed.</p>
<p>There are two specific aspects of the given use case that need to be considered:</p>
<ul>
<li>Electricity consumption primarily occurs during the winter months, when electricity production conditions differ significantly from those in the summer months (e.g., reduced output of photovoltaic systems).</li>
<li>The plant is assumed to have a lifetime of 50 years, which means it is expected to be decommissioned around 2075. Given the European Union’s commitment to achieving net-zero greenhouse gas emissions by 2050, significant changes in the environmental impact of electric energy can be anticipated over the plant’s operational period.</li>
</ul>
<!--To grasp an understanding of the effect of winter conditions on environmental impact of the grid mix, the relevant UVEK-supplied data for operation of storage pumps for hydro plants in winter in several European countries based on energy production technology shares originating from the ENTSO-E Transparency Platform @entsoe_transparency was analysed. Note that these data sets are not directly applicable since the use case is different, but can be used to provide first insights into environmental impact of winter electricity production mix. The relevant data for Germany and Switzerland was used for the analysis. The results show an improvement from 170 Pt per kWh of heat when assuming the ENTSO-E production mix to 166 Pt per kWh of heat for Germany and 145 Pt per kWh of heat for Switzerland based on analysis using the Ecological Scarcity 2021 (v1.04) method. While the exact numbers are not representative, the main insight gathered is that producing winter energy under equal or lower environmental impact than the ENTSO-E production mix is generally feasible in Germany and Switzerland.-->
<p>While attempting to assess the impact of future grid decarbonization, it became apparent that no readily available dataset exists with projections about the future energy grid in Europe that could be directly applied for the analysis. Consequently, the remainder of this section focuses on the planned future for the Swiss energy grid. The most reliable sources of information are provided by the Swiss Federal Office of Energy’s Energy Perspectives 2050+ report <span class="citation" data-cites="bfe2022energieperspektiven">Bundesamt für Energie (BFE) (<a href="#ref-bfe2022energieperspektiven" role="doc-biblioref">2020a</a>)</span> and its accompanying resources including charts <span class="citation" data-cites="bfe2022energieperspektivencharts">Bundesamt für Energie (BFE) (<a href="#ref-bfe2022energieperspektivencharts" role="doc-biblioref">2020b</a>)</span> and data tables <span class="citation" data-cites="bfe2020dataset">Swiss Federal Office of Energy (SFOE) (<a href="#ref-bfe2020dataset" role="doc-biblioref">2020</a>)</span>). Particularly relevant are the projections for the expected winter electricity production mix at five-year intervals from 2025 to 2060, as depicted in <a href="#fig-ch-winter-prod" class="quarto-xref">Figure&nbsp;7</a>.</p>
<div id="fig-ch-winter-prod" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch-winter-prod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_ch_winter.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch-winter-prod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Expected production mix for winter period (6 months) in Switzerland from 2025 to 2060 (Source: Swiss Federal Office for Energy).
</figcaption>
</figure>
</div>
<p>Based on this data, the anticipated energy mix over the operational lifetime of the Bracht plant was calculated as summarized in <a href="#tbl-ch-projection" class="quarto-xref">Table&nbsp;2</a>. Since no projections are available beyond 2060, the values from 2060 were assumed to remain constant through 2075. Detailed information about the origin and type for Switzerland’s imported electricity during the winter was missing from the primary dataset. To adress this, an additional dataset from the World Bank <span class="citation" data-cites="WorldBankWITS2023">World Bank (<a href="#ref-WorldBankWITS2023" role="doc-biblioref">2023</a>)</span> was emplyed to determine the country-wise distribution of electricity imports. According to this dataset, electricity imports in 2023 originated primarily from France (60.2%), Germany (23.1%), Austria (14.4%), and Italy (2.3%). The low voltage production mix in these countries was assumed for modelling. There was no specific data for geothermal and waste water based electricity available. These were substituted with hydro power based electricity, due to its comparable environmental impact profile.</p>
<div id="tbl-ch-projection" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Expected energy mix over the lifetime of the Bracht plant">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-ch-projection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-ch-projection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Type</th>
<th>%</th>
<th>Avg. MWh per year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hydro (with storage pumps)</td>
<td>41.81 %</td>
<td>87.4</td>
</tr>
<tr class="even">
<td>Net imports</td>
<td>22.38 %</td>
<td>46.8</td>
</tr>
<tr class="odd">
<td>PV</td>
<td>20.30 %</td>
<td>42.4</td>
</tr>
<tr class="even">
<td>Wind</td>
<td>4.59 %</td>
<td>9.6</td>
</tr>
<tr class="odd">
<td>Nuclear</td>
<td>3.45 %</td>
<td>7.2</td>
</tr>
<tr class="even">
<td>Fossil (CHP and standalone)</td>
<td>1.73 %</td>
<td>3.6</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>1.70 %</td>
<td>3.6</td>
</tr>
<tr class="even">
<td>Geothermal</td>
<td>1.42 %</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td>From municipal waste</td>
<td>0.92 %</td>
<td>1.9</td>
</tr>
<tr class="even">
<td>Bio gas</td>
<td>1.18 %</td>
<td>2.5</td>
</tr>
<tr class="odd">
<td>Biomass</td>
<td>0.26 %</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>From waste water</td>
<td>0.26 %</td>
<td>0.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Based on the numbers from <a href="#tbl-ch-projection" class="quarto-xref">Table&nbsp;2</a> and evaluated using the Ecological Scarcity 2021 (v1.04) method, the environmental impact of operating such a plant in Switzerland is estimated to an average of 130 Pt per kWh of heat over the complete lifetime of the plant.</p>
<p>To reduce this impact further, the Bracht plant could consider to purchase renewable electricity. Using exclusively wind power would lower the environmental impact to 113 Pt per kWh of heat, while relying solely on hydro power would result in 115 Pt per kWh. In both cases, the environmental footprint associated with the plant’s electricity demand would be largely offset. For comparison, in a hypothetical scenario with no electricity requirement at all, the environmental impact would be 109 Pt per kWh of heat.</p>
</section>
<section id="sec-sensitive-loss" class="level2">
<h2 class="anchored" data-anchor-id="sec-sensitive-loss">Sensitivity analysis: Loss coefficients</h2>
<p>Heat is harder to transport than electrical power since even good insulation cannot avoid losses of radiating heat. There are two main areas where heat losses occur in the setup: in the pipes, and in the seasonal storage unit. Therefore, the loss coefficients assumed for the pipes and for the storage unit are highly relevant to the modelling. The impact of changes in these loss coefficients assumptions will be assessed in <a href="#sec-pipe-loss" class="quarto-xref">Section&nbsp;7.3.1</a> and <a href="#sec-ssu-loss" class="quarto-xref">Section&nbsp;7.3.2</a>.</p>
<section id="sec-pipe-loss" class="level3">
<h3 class="anchored" data-anchor-id="sec-pipe-loss">Pipe heat loss</h3>
<p>As summarized in <span class="citation" data-cites="werner2017international">Werner (<a href="#ref-werner2017international" role="doc-biblioref">2017</a>)</span>, the key parameters affecting heat loss in district heating pipes include the length of the network which depends on the transmission distance relative to demand, the system age, and the operating temperature. The relevant heat loss coefficients reported range between 5 % and 35 %. The Bracht setup involves a relatively long transmission distance of 8800 meters due to its rural context. The planned supply temperature of 85 degrees °C is relatively high and will contribute to increased thermal losses. In contrast, modern district heating systems can operate with lower supply temperatures between 50 and 70 degrees °C to minimize heat loss and improve efficiency <span class="citation" data-cites="lund2020districtheating">Lund et al. (<a href="#ref-lund2020districtheating" role="doc-biblioref">2020</a>)</span>.</p>
<p>The rationale behind selecting a default heat loss rate of 20 % for the Bracht setup reflects the combined negative impact of the long transmission distance and high operating temperature on system performance. However, several sources assume lower loss rates. For example, the open source Energy Transition Model <span class="citation" data-cites="etm2025">Quintel (<a href="#ref-etm2025" role="doc-biblioref">2025</a>)</span> suggests a 15 % default loss figure based on real world data for modern district heating networks. The Swiss Federal Office of Energy UVEK assumes an even lower rate of approximately 11 % in its district heating data.</p>
<p>If the Bracht system was optimized to achieve heat loss rates comparable to the UVEK assumption, e.g.&nbsp;by lowering the operating temperature, annual efficiency gains of about 300 MWh could be realized. This would remove one-third of the requirements planned to be supplied via biomass, which would correspond to a 9 % reduction in ecological impact from 170 Pt per kWh to 155 Pt per kWh of heat produced according to the Ecological Scarcity 2021 (v1.04) method at the single score level with UVEK LCI weighting. The most significant reductions can be achieved in the <em>Main air pollutants and Particulate Matter (PM)</em> category, primarily due to the reduced combustion of biomass.</p>
<!-- Biomass: other uses such as CO2 storage or trees growing are prevented -->
</section>
<section id="sec-ssu-loss" class="level3">
<h3 class="anchored" data-anchor-id="sec-ssu-loss">Seasonal storage unit heat loss</h3>
<p>In <span class="citation" data-cites="penttinen2021optimal">Penttinen et al. (<a href="#ref-penttinen2021optimal" role="doc-biblioref">2021</a>)</span>, the authors report a 26 % loss of heat production in the storage unit amounted to of heat production. The Energy Transition Model <span class="citation" data-cites="etm2025">Quintel (<a href="#ref-etm2025" role="doc-biblioref">2025</a>)</span> suggests 30 % as a sensible default for modelling heat loss in the storage unit. Another study <span class="citation" data-cites="xiang2022comprehensive">Xiang et al. (<a href="#ref-xiang2022comprehensive" role="doc-biblioref">2022</a>)</span> provides a comprehensive review and finds that 30% to 50% heat loss are common for Pit Thermal Energy Storage and that the majority of losses are caused through the top of the system, where the floating cover is located.</p>
<p>Given these reference numbers from literature, the 50 % loss assumption that was used for the Bracht plant is on the conservative side. For the sensitivity analysis, the assumption made is that it can potentially be lowered to 30% based on two different scenarios: (A) without any changes in the setup but an understanding that the original assumptions were not accurate, and (B) by doubling the floating cover for the top of the seasonal storage unit which will provide better insulation. Sides and bottom of the seasonal storage unit remain unchanged.</p>
<p>In both scenarios, a significantly higher amount of energy is available from the seasonal storage unit because of the lower heat loss as shown in <a href="#tbl-loss" class="quarto-xref">Table&nbsp;3</a>. In the original scenario, out of the 4.517 MWh produced by the solar thermal collectors, an amount of 2.259 MWh remains available from the seasonal storage unit after accounting for assumed losses. When heat losses are reduced, the available energy increases substantially to 3.162 MWh. The difference of 900 MWh is equal in size to the contribution that was expected to be supplied via biomass combustion in the default model. Therefore, the opportunity exists to lower the environmental impact of the system by removing the parts that stem from biomass. These have a significant impact as shown in <a href="#sec-results" class="quarto-xref">Section&nbsp;6</a>.</p>
<div id="tbl-loss" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="SSU heat loss">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-loss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-loss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Dimension</th>
<th>Value</th>
<th>Assumed loss</th>
<th>Electricity requirements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>Produced</td>
<td>4.517 MWh</td>
<td>-</td>
<td></td>
</tr>
<tr class="even">
<td>default</td>
<td>Available</td>
<td>2.259 MWh</td>
<td>50%</td>
<td>209 MWh (Factor 0.092)</td>
</tr>
<tr class="odd">
<td>(A) and (B)</td>
<td>Available</td>
<td>3.162 MWh</td>
<td>30%</td>
<td>293 MWh (Factor 0.092)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>However, the higher availability of energy in the seasonal storage unit results in a modified heat supply curve and in heightened electrical energy requirements for the heat pump since it will be used more extensively in the system instead of the biomass boiler. An in-depth analysis of the implications would require additional modelling tools such as <span class="citation" data-cites="polysun">AG (<a href="#ref-polysun" role="doc-biblioref">2012</a>)</span>, which is out of scope for the given work. As a simplification, a rough estimate of the heightened energy requirements was carried out based the factor between energy from the seasonal storage unit and energy from electricity from the original assumptions (see <a href="#tbl-loss" class="quarto-xref">Table&nbsp;3</a>): 209 MWh divided by 2.258 MWh, which returns a 9.2 % electricity requirement factor. Note that this corresponds to a COP of 11, which is indicative for a highly performant system. This was considered plausible, because the initially very high temperature in the seasonal storage unit (85 degrees °C) at begin of the heating periods means that the heat pump will not be required to bridge the temperature gap until the temperatures are falling to lower levels. The rough estimate based on the electricity requirement factor as described results in a 293 MWh electricity demand for the heat pump (40 % increase).</p>
<p>Both scenarios were modeled in SimaPro to learn about the implications on environmental impact. Like in the default model, the ENTSO-E production mix was assumed. For scenario (A) with updated assumptions, a 15 % reduction from 170 Pt per kWh of heat to 146 Pt per kWh of heat can be achieved. For scenario (B) with a doubled insulating cover for the seasonal storage unit, a 9 % reduction to 155<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Pt per kWh of heat can be achieved. This confirms the environmental impact savings potential of operating conditions improvements.</p>
</section>
</section>
<section id="sec-combined" class="level2">
<h2 class="anchored" data-anchor-id="sec-combined">Combined results from sensitivity analysis</h2>
<p>As discussed in the previous sections, two main opportunities for optimization have been identified: (1) using renewable energy to operate the heat pump and (2) reducing heat losses in the system to decrease the need for supplemental biomass. However, improving insulation leads to increased electricity demand for the heat pump which in turn amplifies the benefits of using renewable energy.</p>
<p>Given the interdependence of these two factors, this section presents the combined results. The analysis is based on the IPCC 2021 GWP100 methodology <span class="citation" data-cites="IPCC_2021_WGI_Annex_III">Dentener et al. (<a href="#ref-IPCC_2021_WGI_Annex_III" role="doc-biblioref">2021</a>)</span>, with outcomes expressed in grams of CO₂-equivalents per kWh, to enable comparison with widely recognized tools such as <span class="citation" data-cites="electricitymaps">ApS (<a href="#ref-electricitymaps" role="doc-biblioref">2025</a>)</span>. However, it is important to note that heat and electricity are different energy forms, which should be considered when interpreting direct comparisons. As the results for wind and hydro power were nearly identical, hydro was excluded from this analysis for the sake of clarity. Scenario (A) from <a href="#sec-ssu-loss" class="quarto-xref">Section&nbsp;7.3.2</a> was chosen for the comparison as the representative scenario for heat loss optimization. The results are presented in <a href="#fig-combined" class="quarto-xref">Figure&nbsp;8</a>. The chart reveals that, according to the IPCC methodology, scenario (A) performs worse than the baseline due to increased electricity demand met by the ENTSO-E production mix. However, this impact can be mitigated by using wind energy, which in turn yields the best results among the scenarios compared by bringing down the numbers substantially, from 72 g CO₂-eq for the ENTSO-E based baseline to 31 g CO₂-eq for the heat loss optimized scenario together with renewable energy from wind.</p>
<div id="fig-combined" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-combined-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_ipcc.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-combined-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Environmental impact in grams of CO₂-eq per kWh of heat (IPCC 2021 GWP100).
</figcaption>
</figure>
</div>
</section>
</section>
<section id="summary-and-conclusion" class="level1">
<h1>Summary and conclusion</h1>
<p>A Life cycle impact assessment was conducted for a solar district heating community project located in Bracht, Rauschenberg, Germany. This project combines solar thermal collectors with a seasonal storage unit to preserve heat produced in summer until the heating period in fall and winter. A district heating distribution network supplies the thermal energy to 180 residential consumers. The system’s energy supply is expected to be to the largest share from stored solar thermal energy, partly from biomass, and partly from the electricity grid. Default modelling assumptions included a 20 % heat loss coefficient for the district heating network and an implied 50 % loss for the seasonal storage unit.</p>
<p>Results indicate that biomass and grid electricity are the primary contributors to the overall environmental impact, accounting for approximately two-thirds of the total, despite supplying only one-third of the energy delivered. The solar thermal collectors contribute less than 15 % to the overall environmental impact. Analysis by damage categories shows biomass combustion significantly contributes to land use, particulate matter, and terrestrial eutrophication, while electricity use is the main driver for fossil resource use and climate change.</p>
<p>Comparing the Bracht system to other heating technologies, the STC-based district heating system with seasonal storage shows the second lowest environmental impact at approximately 170 Pt per kilowatt-hour (kWh) of heat, based on analysis using the Ecological Scarcity 2021 (v1.04) method. This is similar to district heating using wood chips (165 Pt/kWh), lower than a geothermal heat pump district heating system (225 Pt/kWh), and significantly lower than gas boilers (281 Pt/kWh) and oil boilers (430 Pt/kWh).</p>
<p>Sensitivity analyses for the inputs biomass and electricity were performed to demonstrate the effects of generalizations and uncertainties in input data on the results, and to evaluate the potential for reducing environmental impact. The conclusion is that, while the Bracht solar district heating system compares favorably to many conventional and alternative heating technologies in terms of environmental impact, further improvements to the operating conditions are possible to achieve even lower environmental impact.</p>
<p>Significant opportunities lie in sourcing lower-emission electricity for heat pump operation, which would help mitigate the environmental impact associated with the current and future electric grid mix. Purchasing of renewable energy for the operation of the heat pump achieves highly significant improvements.</p>
<p>Furthermore, improving heat loss coefficients, particularly reducing the significant heat loss in the seasonal storage unit, could allow the system to meet consumer demand without any combustion of supplemental biomass over the winter heating period, which would also achieve sizable savings in environmental impact. The first step towards achieving this is to use dedicated modelling tools to fully understand the impact of the different operating conditions on the energy balance to validate the preliminary findings of this study. In addition, since the plant will be entering the operational phase in late 2025, further analysis can be supported with run-time data collected from the functional system.</p>
</section>
<section id="appendix-and-supporting-information" class="level1">
<h1>Appendix and supporting information</h1>
<p>This section documents the supporting information related to the life cycle inventory in <a href="#sec-lci" class="quarto-xref">Section&nbsp;9.1</a>, the data used for modelling in <a href="#sec-data" class="quarto-xref">Section&nbsp;9.2</a>, supplemental charts in <a href="#sec-charts" class="quarto-xref">Section&nbsp;9.3</a>, and the project organization in <a href="#sec-project" class="quarto-xref">Section&nbsp;9.4</a>.</p>
<section id="sec-lci" class="level2">
<h2 class="anchored" data-anchor-id="sec-lci">Life cycle inventory</h2>
<p>There are several components described in the following sections: solar thermal collector, seasonal storage unit, and heat preparation.</p>
<section id="solar-thermal-collector-stc" class="level3">
<h3 class="anchored" data-anchor-id="solar-thermal-collector-stc">Solar thermal collector (STC)</h3>
<p>The relevant data for the solar thermal collector can be found in <a href="#tbl-component-stc" class="quarto-xref">Table&nbsp;4</a>.</p>
<div id="tbl-component-stc" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Sources for solar thermal collector specification">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-component-stc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-component-stc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Size</td>
<td>11’638 <span class="math inline">\(m^2\)</span> (855 x 13.6 <span class="math inline">\(m^2\)</span>)</td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span></td>
</tr>
<tr class="even">
<td>Type</td>
<td>Flat-plate collectors Vitosol 100-F XF13 Viessmann</td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span> <span class="citation" data-cites="viessmann2021">(<a href="#ref-viessmann2021" role="doc-biblioref">Viessmann Climate Solutions, 2021</a>)</span> <span class="citation" data-cites="tuev2021">(<a href="#ref-tuev2021" role="doc-biblioref">TÜV Rheinland, 2021</a>)</span></td>
</tr>
<tr class="odd">
<td>Land use</td>
<td>23.500 <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span></td>
</tr>
<tr class="even">
<td>Mounting infrastructure material</td>
<td>15 t steel</td>
<td><span class="citation" data-cites="bracht2025">(<a href="#ref-bracht2025" role="doc-biblioref">City of Rauschenberg, 2025c</a>)</span></td>
</tr>
<tr class="odd">
<td>Collector weight</td>
<td>50 kg / <span class="math inline">\(m^2\)</span></td>
<td>Own assumption</td>
</tr>
<tr class="even">
<td>Production country</td>
<td>China</td>
<td>Own assumption</td>
</tr>
<tr class="odd">
<td>Transport per container ship</td>
<td>8000 km</td>
<td>Own assumption</td>
</tr>
<tr class="even">
<td>Transport per lorry</td>
<td>1000 km</td>
<td>Own assumption</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="seasonal-storage-unit-ssu" class="level3">
<h3 class="anchored" data-anchor-id="seasonal-storage-unit-ssu">Seasonal storage unit (SSU)</h3>
<p>The relevant data for the seasonal storage unit can be found in <a href="#tbl-component-ssu" class="quarto-xref">Table&nbsp;5</a>. A picture of the floating cover can be found in <a href="#fig-floating-cover" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div id="fig-floating-cover" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-floating-cover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/floating_cover.jpg" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-floating-cover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Floating cover profile. Source: Bracht community.
</figcaption>
</figure>
</div>
<div id="tbl-component-ssu" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Sources for seasonal storage unit specification">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-component-ssu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5
</figcaption>
<div aria-describedby="tbl-component-ssu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Volume</td>
<td>26’600 <span class="math inline">\(m^3\)</span></td>
<td><span class="citation" data-cites="epp2024high">(<a href="#ref-epp2024high" role="doc-biblioref">Epp, 2024</a>)</span></td>
</tr>
<tr class="even">
<td>Resource: water</td>
<td>26’600 <span class="math inline">\(m^3\)</span> filled from local source</td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span></td>
</tr>
<tr class="odd">
<td>Cover layer 1, 10</td>
<td>Polyethylen (HDPE) sealing membranes 1.5 mm, 1.5 kg / <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span>, estimated weight</td>
</tr>
<tr class="even">
<td>Cover layer 2, 9</td>
<td>Fleece (0.1 kg / <span class="math inline">\(m^2\)</span>) laminated plastic grid (HDPE, 0.5 kg / <span class="math inline">\(m^2\)</span>)</td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span>, estimated weight</td>
</tr>
<tr class="odd">
<td>Cover layer 3</td>
<td>Foam glass, 8.33 kg / <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span></td>
</tr>
<tr class="even">
<td>Cover layer 4</td>
<td>Polyurethane (bauder foam): 3.125 kg / <span class="math inline">\(m\^2\)</span></td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span></td>
</tr>
<tr class="odd">
<td>Cover layer 5, 7, 8</td>
<td>Airing gap made of plastic grid, 0.5 kg / <span class="math inline">\(m^2\)</span> each</td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span>, estimated weight</td>
</tr>
<tr class="even">
<td>Cover layer 6</td>
<td>Polystyrene (XPS), 3 kg / <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span></td>
</tr>
<tr class="odd">
<td>Floating cover dimensions</td>
<td>70 m x 70 m = 4900 <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025ground">(<a href="#ref-bracht2025ground" role="doc-biblioref">Top Agrar, 2025</a>)</span></td>
</tr>
<tr class="even">
<td>Floating cover weight</td>
<td>2 * (1.5 + 0.1 + 0.5) + 8.33 + 3.125 + 1.5 + 3 = 20.155 kg / <span class="math inline">\(m^2\)</span></td>
<td>Calculation</td>
</tr>
<tr class="odd">
<td>Ground liner</td>
<td>Polyethylen (HDPE), 2.5mm, 2.5 kg / <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025floating">(<a href="#ref-bracht2025floating" role="doc-biblioref">City of Rauschenberg, 2025b</a>)</span>, estimated weight</td>
</tr>
<tr class="even">
<td>Ground liner dimensions</td>
<td>Bottom 20 m x 20 m, vertical height 15 m, surface area on each of the four sides 5250 <span class="math inline">\(m^2\)</span></td>
<td><span class="citation" data-cites="bracht2025ground">(<a href="#ref-bracht2025ground" role="doc-biblioref">Top Agrar, 2025</a>)</span></td>
</tr>
<tr class="odd">
<td>Ground liner weight</td>
<td>2.5 kg / <span class="math inline">\(m^2\)</span></td>
<td>Assumption</td>
</tr>
<tr class="even">
<td>Production country</td>
<td>China</td>
<td>Assumption</td>
</tr>
<tr class="odd">
<td>Transport per container ship</td>
<td>8000 km</td>
<td>Assumption</td>
</tr>
<tr class="even">
<td>Transport per lorry</td>
<td>1000 km</td>
<td>Assumption</td>
</tr>
<tr class="odd">
<td>Required construction process</td>
<td>Excavator 26.600 <span class="math inline">\(m^3\)</span></td>
<td><span class="citation" data-cites="epp2024high">(<a href="#ref-epp2024high" role="doc-biblioref">Epp, 2024</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-hp" class="level3">
<h3 class="anchored" data-anchor-id="sec-hp">Heat preparation</h3>
<p>The relevant data for the heat preparation unit can be found in <a href="#tbl-component-hp" class="quarto-xref">Table&nbsp;6</a>.</p>
<div id="tbl-component-hp" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Sources for seasonal storage unit specification">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-component-hp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6
</figcaption>
<div aria-describedby="tbl-component-hp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 55%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Value</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Heat pump</td>
<td>2x Carrier Aquaforce 61XWH-ZE (630 kW max electrical input power)</td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span> <span class="citation" data-cites="carrier2025floating">(<a href="#ref-carrier2025floating" role="doc-biblioref">Carrier Klimatisierungs- und Heizsysteme Deutschland, 2025</a>)</span></td>
</tr>
<tr class="even">
<td>Electricity requirements</td>
<td>209 MWh per year</td>
<td>Own calculation, see <a href="#sec-loss-coefficients" class="quarto-xref">Section&nbsp;5.2</a></td>
</tr>
<tr class="odd">
<td>Buffer storage</td>
<td>ca. 200 <span class="math inline">\(m^3\)</span> = 200’000 l</td>
<td><span class="citation" data-cites="epp2024high">(<a href="#ref-epp2024high" role="doc-biblioref">Epp, 2024</a>)</span></td>
</tr>
<tr class="even">
<td>Biomass boiler</td>
<td>Mawera boiler with 700 kW thermal power</td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span></td>
</tr>
<tr class="odd">
<td>Controller</td>
<td>Vitocontrol 200-M</td>
<td><span class="citation" data-cites="viessmann2024">(<a href="#ref-viessmann2024" role="doc-biblioref">Viessmann Climate Solutions, 2024</a>)</span> <span class="citation" data-cites="viessmann2025">(<a href="#ref-viessmann2025" role="doc-biblioref">Viessmann Climate Solutions, 2025</a>)</span></td>
</tr>
<tr class="even">
<td>Heat installation facility</td>
<td>50 <span class="math inline">\(m^2\)</span></td>
<td>Own assumption</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-data" class="level2">
<h2 class="anchored" data-anchor-id="sec-data">Data</h2>
<p>In this section, the data that was created for the model is documented.</p>
<section id="sec-sima" class="level3">
<h3 class="anchored" data-anchor-id="sec-sima">SimaPro data</h3>
<p><a href="#tbl-sima-parameters" class="quarto-xref">Table&nbsp;7</a> and <a href="#tbl-sima-calc-parameters" class="quarto-xref">Table&nbsp;8</a> show the parameters and calculated parameters that were defined as helpers for modelling the solar thermal based district heating process in Simpapro.</p>
<p>The data for the process <em>district heat, at consumer, solar thermal, 1MW/MJ/RER U</em> is kept in an external spreadsheet <a href="https://docs.google.com/spreadsheets/d/11BHntxbclWm44ycV1JyY0AiQ9LamUJ2PbaCSZOzd-VE/edit?gid=311795711#gid=311795711">accessible here</a>. The data for the sensitivity analysis process can be found in a separate tab <a href="https://docs.google.com/spreadsheets/d/11BHntxbclWm44ycV1JyY0AiQ9LamUJ2PbaCSZOzd-VE/edit?gid=564209798#gid=564209798">accessible here</a>.</p>
<div id="tbl-sima-parameters" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Parameters defined in SimaPro">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-sima-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7
</figcaption>
<div aria-describedby="tbl-sima-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Value</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Plant-size-m2</td>
<td>23500</td>
<td>The total size of the plant in sqm</td>
</tr>
<tr class="even">
<td>STC-size-m2</td>
<td>11638</td>
<td>The total size of the STC panels in sqm</td>
</tr>
<tr class="odd">
<td>STC-weight-per-m2</td>
<td>50</td>
<td>The weight of the STC per sqm</td>
</tr>
<tr class="even">
<td>STC-prod-MWh-per-a</td>
<td>2700</td>
<td>Production from the STC per year in MWh</td>
</tr>
<tr class="odd">
<td>Lifetime</td>
<td>50</td>
<td>The lifetime of the plant in years</td>
</tr>
<tr class="even">
<td>MWhtoMJ</td>
<td>3600</td>
<td>Conversion from MWh to MJ</td>
</tr>
<tr class="odd">
<td>Mult30To50</td>
<td>1.67</td>
<td>Multiplier for components with 30 years lifetime</td>
</tr>
<tr class="even">
<td>Mult20To50</td>
<td>2.5</td>
<td>Multiplier for components with 20 years lifetime</td>
</tr>
<tr class="odd">
<td>SSU-volume-m3</td>
<td>26600</td>
<td>The volume of the SSU</td>
</tr>
<tr class="even">
<td>SSU-top-m2</td>
<td>4900</td>
<td>The size of the SSU at the top (floating cover) in sqm</td>
</tr>
<tr class="odd">
<td>SSU-side-m2</td>
<td>5250</td>
<td>The size of the SSU at each of the four sides in sqm</td>
</tr>
<tr class="even">
<td>SSU-bottom-m2</td>
<td>5400</td>
<td>The size of the SSU at the ground in sqm</td>
</tr>
<tr class="odd">
<td>Steel-kg</td>
<td>15000</td>
<td>The weight of the required steel for the STC foundation</td>
</tr>
<tr class="even">
<td>Freight-ship-dist-km</td>
<td>8000</td>
<td>The transport distance per freight ship in km</td>
</tr>
<tr class="odd">
<td>Lorry-dist-km</td>
<td>1000</td>
<td>The transport distance per lorry in km</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-sima-calc-parameters" class="table quarto-float quarto-figure quarto-figure-center anchored" data-caption="Calculated parameters defined in SimaPro">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-sima-calc-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8
</figcaption>
<div aria-describedby="tbl-sima-calc-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 31%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Value</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>STC-prod-MJ-lifetime</td>
<td>STC-prod-MWh-per-a * Lifetime * MWhtoMJ</td>
<td>The total production from the STC over the plant lifetime in MJ</td>
</tr>
<tr class="even">
<td>STC-weight-t-total</td>
<td>(STC-size-m2 * STC-weight-per-m2 * Mult30To50 + Steel-kg) / 1000</td>
<td>The total transport weight of the STC over the plant lifetime in tons</td>
</tr>
<tr class="odd">
<td>SSU-ground-m2</td>
<td>SSU-bottom-m2 + 4 * SSU-side-m2</td>
<td>The total size of the SSU that is touching the ground on the bottom and sides in sqm</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For the comparison, the following SimaPro processes were employed (all of them part of the UVEK dataset):</p>
<ul>
<li><em>district heat, at consumer, borehole heat pump, 50kW/MJ/CH U</em></li>
<li><em>district heat, at consumer, wood chips in industrial furnace, 1MW/MJ/CH U</em></li>
<li><em>heat, light fuel oil, at boiler 10kW, average/CH U</em></li>
<li><em>heat, natural gas, at boiler condensating modulating, 15kW/CH U</em></li>
</ul>
<p>For the electricity sensitivity analysis, the following SimaPro processes were employed for comparison:</p>
<ul>
<li><em>electricity, low voltage, production from hydro power, at grid/CH U</em></li>
<li><em>Electricity, at wind power plant/CH U</em></li>
</ul>
</section>
<section id="loss-coefficients-and-energy-requirements" class="level3">
<h3 class="anchored" data-anchor-id="loss-coefficients-and-energy-requirements">Loss coefficients and energy requirements</h3>
<p>The loss coefficients and energy requirements numbers were calculated in a spreadsheet accessible <a href="https://docs.google.com/spreadsheets/d/1UTKZtQ1wE8QxeNJFWMrw3FbvYS9aZiGvNbqz4s6s35Y/edit?gid=0#gid=0">here</a>.</p>
</section>
<section id="results-data" class="level3">
<h3 class="anchored" data-anchor-id="results-data">Results data</h3>
<p>The data for producing the charts for this report is kept in a spreadsheet accessible <a href="https://docs.google.com/spreadsheets/d/1Ghai0-kHUOZTMoKDRJ7uO3ejAa72vN2kFpBa4IFHCks/edit?gid=0#gid=0">here</a>, with one or more tabs in the spreadsheet for each figure.</p>
</section>
</section>
<section id="sec-charts" class="level2">
<h2 class="anchored" data-anchor-id="sec-charts">Supplemental charts</h2>
<p>In this section, supplemental charts are presented for completeness reasons. <a href="#fig-ef-midpoints-others" class="quarto-xref">Figure&nbsp;10</a> complements <a href="#fig-ef-midpoints" class="quarto-xref">Figure&nbsp;6</a> with the results for the damage categories that were considered less relevant for the use case.</p>
<div id="fig-ef-midpoints-others" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ef-midpoints-others-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/pwrg_solar_ef_midpoints_faceted_others.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ef-midpoints-others-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Damage assessment using the Environmental Footprint Method, visualized as relative environmental impacts in comparison.
</figcaption>
</figure>
</div>
</section>
<section id="sec-project" class="level2">
<h2 class="anchored" data-anchor-id="sec-project">Project organization</h2>
<p>In this section, the time plan and the meeting notes are documented.</p>
<section id="time-planning" class="level3">
<h3 class="anchored" data-anchor-id="time-planning">Time planning</h3>
<p><a href="#fig-time-plan" class="quarto-xref">Figure&nbsp;11</a> documents the time plan that was followed for this project. The live version can be found <a href="https://docs.google.com/spreadsheets/d/1GXiuAFEArfoSObDDMjL8yixMMKVGG254yvQUYm0Jduc/edit?gid=1314943303#gid=1314943303">here</a>.</p>
<div id="fig-time-plan" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/time_plan.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-plan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Gantt chart used for time planning.
</figcaption>
</figure>
</div>
</section>
<section id="meeting-notes" class="level3">
<h3 class="anchored" data-anchor-id="meeting-notes">Meeting notes</h3>
<p>The notes for the meetings can be found <a href="https://docs.google.com/document/d/1ckpCeTboJK6gfoXQi750jMr5Y85_x3PROEDG1IKEM4E/edit?tab=t.0#heading=h.ibakwauq0483">here</a>. Access is given upon request. Contact in case of permission issues: Elke Michlmayr.</p>
</section>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-abokersh2020framework" class="csl-entry" role="listitem">
Abokersh, M. H., Vallès, M., Cabeza, L. F., and Boer, D. (2020). A framework for the optimal integration of solar assisted district heating in different urban sized communities: A robust machine learning approach incorporating global sensitivity analysis. <em>Applied Energy</em>, <em>267</em>, 114903.
</div>
<div id="ref-polysun" class="csl-entry" role="listitem">
AG, V. S. (2012). <em>Polysun simulation software</em>. <a href="https://www.velasolaris.com" class="uri">https://www.velasolaris.com</a>.
</div>
<div id="ref-electricitymaps" class="csl-entry" role="listitem">
ApS, E. M. (2025). <em>Electricity maps</em>. <a href="https://app.electricitymaps.com/map/72h/hourly">https://app.electricitymaps.com/map/72h/hourly</a>
</div>
<div id="ref-bfe2022energieperspektiven" class="csl-entry" role="listitem">
Bundesamt für Energie (BFE). (2020a). <em>Energieperspektiven 2050+</em>. Bundesamt für Energie. <a href="https://www.bfe.admin.ch/bfe/de/home/politik/energieperspektiven-2050-plus.html">https://www.bfe.admin.ch/bfe/de/home/politik/energieperspektiven-2050-plus.html</a>
</div>
<div id="ref-bfe2022energieperspektivencharts" class="csl-entry" role="listitem">
Bundesamt für Energie (BFE). (2020b). <em>Energieperspektiven 2050+: Entwicklung der stromproduktion</em>. Bundesamt für Energie. <a href="https://www.uvek-gis.admin.ch/BFE/storymaps/AP_Energieperspektiven/index3.html?lang=de&amp;selectedSzenario=ZB&amp;selectedVariant=AJB&amp;selectedNuclear=50">https://www.uvek-gis.admin.ch/BFE/storymaps/AP_Energieperspektiven/index3.html?lang=de&amp;selectedSzenario=ZB&amp;selectedVariant=AJB&amp;selectedNuclear=50</a>
</div>
<div id="ref-carrier2025floating" class="csl-entry" role="listitem">
Carrier Klimatisierungs- und Heizsysteme Deutschland. (2025). <em><span class="nocase">AquaForce Hochtemperatur Wasser/Wasser-Wärmepumpe mit Kältemittel HFO R-1234ze</span></em>. <a href="https://www.carrier.com/commercial/de/de/produkte/heizung/wasser-wasser-waermepumpen/61xwhze/" class="uri">https://www.carrier.com/commercial/de/de/produkte/heizung/wasser-wasser-waermepumpen/61xwhze/</a>.
</div>
<div id="ref-bracht2025faq" class="csl-entry" role="listitem">
City of Rauschenberg. (2025a). <em><span class="nocase">Solarwärme Bracht eG, FAQ und häufig gestellte Fragen</span></em>. <a href="https://www.solarwaerme-bracht.de/faq/" class="uri">https://www.solarwaerme-bracht.de/faq/</a>.
</div>
<div id="ref-bracht2025floating" class="csl-entry" role="listitem">
City of Rauschenberg. (2025b). <em><span class="nocase">Solarwärme Bracht eG, Genossenschaftsunterlagen: Floating Cover</span></em>. <a href="https://www.solarwaerme-bracht.de/unterlagen-der-genossenschaft/" class="uri">https://www.solarwaerme-bracht.de/unterlagen-der-genossenschaft/</a>.
</div>
<div id="ref-bracht2025" class="csl-entry" role="listitem">
City of Rauschenberg. (2025c). <em><span class="nocase">Solarwärme Bracht eG, Stadtteile Bracht und Bracht-Siedlung</span></em>. <a href="https://www.solarwaerme-bracht.de/" class="uri">https://www.solarwaerme-bracht.de/</a>.
</div>
<div id="ref-IPCC_2021_WGI_Annex_III" class="csl-entry" role="listitem">
Dentener, F. J., Hall, B., Smith, C., Ahn, J., Collins, W., Jones, C. D., and Meinshausen, M. (2021). Tables of historical and projected well-mixed greenhouse gas mixing ratios and effective radiative forcing of all climate forcers. In V. Masson-Delmotte, P. Zhai, A. Pirani, S. L. Connors, C. Péan, S. Berger, N. Caud, Y. Chen, L. Goldfarb, M. I. Gomis, M. Huang, K. Leitzell, E. Lonnoy, J. B. R. Matthews, T. K. Maycock, T. Waterfield, O. Yelekçi, R. Yu, and B. Zhou (Eds.), <em>Climate change 2021: The physical science basis. Contribution of working group i to the sixth assessment report of the intergovernmental panel on climate change</em> (pp. 2139–2151). Cambridge University Press. <a href="https://doi.org/10.1017/9781009157896.017">https://doi.org/10.1017/9781009157896.017</a>
</div>
<div id="ref-epp2024high" class="csl-entry" role="listitem">
Epp, B. (2024). <em><span class="nocase">High Solar Heat Fraction Solutions Supported by Heat Pumps</span></em>. <a href="https://solarthermalworld.org/news/high-solar-heat-fraction-solutions-supported-by-heat-pumps/" class="uri">https://solarthermalworld.org/news/high-solar-heat-fraction-solutions-supported-by-heat-pumps/</a>.
</div>
<div id="ref-euroheat2023" class="csl-entry" role="listitem">
Euroheat &amp; Power. (2023). <em>28/03/2023: The rise of solar district heating</em>. <a href="https://www.youtube.com/watch?v=ngNgVxTT2y4" class="uri">https://www.youtube.com/watch?v=ngNgVxTT2y4</a>.
</div>
<div id="ref-ec2021EF" class="csl-entry" role="listitem">
European Commission. (2021). <em><span class="nocase">Commission Recommendation (EU) 2021/2279 of 15 December 2021 on the use of the Environmental Footprint methods to measure and communicate the life cycle environmental performance of products and organisations</span></em>. <a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32021H2279" class="uri">https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32021H2279</a>.
</div>
<div id="ref-famiglietti2021environmental" class="csl-entry" role="listitem">
Famiglietti, J., Gerevini, L., Spirito, G., Pozzi, M., Dénarié, A., Scoccia, R., and Motta, M. (2021). Environmental life cycle assessment scenarios for a district heating network. An italian case study. <em>Energy Reports</em>, <em>7</em>, 368–379.
</div>
<div id="ref-FOEN2021" class="csl-entry" role="listitem">
Federal Office for the Environment (FOEN). (2021). <em>Swiss eco-factors 2021 according to the ecological scarcity method: Methodological fundamentals and their application in switzerland</em>. <a href="https://www.bafu.admin.ch/bafu/en/home/topics/economy-consumption/economy-and-consumption-publications/publications-economy-and-consumption/eco-factors-switzerland.html">https://www.bafu.admin.ch/bafu/en/home/topics/economy-consumption/economy-and-consumption-publications/publications-economy-and-consumption/eco-factors-switzerland.html</a>
</div>
<div id="ref-FOEN2025" class="csl-entry" role="listitem">
Federal Office for the Environment (FOEN). (2025). <em>UVEK LCI database DQRv2:2025</em>.
</div>
<div id="ref-grosse2017long" class="csl-entry" role="listitem">
Große, R., Binder, C., Wöll, S., Geyer, R., and Robbi, S. (2017). <em>Long term (2050) projections of techno-economic performance of large-scale heating and cooling in the EU</em>. Publications Office of the European Union.
</div>
<div id="ref-jeandaux2021life" class="csl-entry" role="listitem">
Jeandaux, C., Videau, J.-B., and Prieur-Vernat, A. (2021). Life cycle assessment of district heating systems in europe: Case study and recommendations. <em>Sustainability</em>, <em>13</em>(20), 11256.
</div>
<div id="ref-bracht2022" class="csl-entry" role="listitem">
Kelch, J., Kusyy, O., Orozaliev, J., and Vajen, K. (2022). <em>Abschlussbericht weiterentwicklung und optimierung des konzepts einer solaren nahwärmeversorgung für ländliche gebiete am beispiel von bracht-dorf</em> (Technical Report EF960 0039/2021 20008503). Universität Kassel.
</div>
<div id="ref-kelch2024comparison" class="csl-entry" role="listitem">
Kelch, J., Kusyy, O., Zipplies, J., Orozaliev, J., and Vajen, K. (2024). Comparison of solar district heating and renovation of buildings as measures for decarbonization of heat supply in rural areas. <em>Solar Energy Advances</em>, <em>4</em>, 100060.
</div>
<div id="ref-lund2020districtheating" class="csl-entry" role="listitem">
Lund, H., Werner, S., Wiltshire, R., Svendsen, S., Thorsen, J. E., Hvelplund, F., and Mathiesen, B. V. (2020). District heating and cooling: Review of technology and potential enhancements. <em>Energy</em>, <em>68</em>, 1–11. <a href="https://doi.org/10.1016/j.energy.2014.05.045">https://doi.org/10.1016/j.energy.2014.05.045</a>
</div>
<div id="ref-penttinen2021optimal" class="csl-entry" role="listitem">
Penttinen, P., Vimpari, J., and Junnila, S. (2021). Optimal seasonal heat storage in a district heating system with waste incineration. <em>Energies</em>, <em>14</em>(12), 3522.
</div>
<div id="ref-SimaPro2024" class="csl-entry" role="listitem">
PRé Sustainability. (2024). <em>SimaPro 9.6 database manual: Methods library</em>. <a href="https://simapro.com/wp-content/uploads/2024/04/DatabaseManualMethods.pdf">https://simapro.com/wp-content/uploads/2024/04/DatabaseManualMethods.pdf</a>
</div>
<div id="ref-etm2025" class="csl-entry" role="listitem">
Quintel. (2025). <em><span>Energy Transition Model (ETM)</span></em>. <a href="https://energytransitionmodel.com/scenario/supply/heat_ht/transport-and-distribution-losses" class="uri">https://energytransitionmodel.com/scenario/supply/heat_ht/transport-and-distribution-losses</a>.
</div>
<div id="ref-solano2023life" class="csl-entry" role="listitem">
Solano, J., Frossard, M., Lasvaux, S., and Duret, A. (2023). Life cycle assessment of the new solar thermal power plant SolarCAD II connected to a district heating network in geneva, switzerland. <em>Journal of Physics: Conference Series</em>, <em>2600</em>, 152005.
</div>
<div id="ref-sfoe2020" class="csl-entry" role="listitem">
Swiss Federal Office of Energy. (2020). <em>District heat</em>. <a href="https://www.bfe.admin.ch/bfe/en/home/supply/energy-efficiency/district-heat.html" class="uri">https://www.bfe.admin.ch/bfe/en/home/supply/energy-efficiency/district-heat.html</a>.
</div>
<div id="ref-bfe2020dataset" class="csl-entry" role="listitem">
Swiss Federal Office of Energy (SFOE). (2020). <em>Energy perspectives 2050+: Scenario results ZERO basis (ZIP dataset)</em>. <a href="https://www.bfe.admin.ch/bfe/de/home/politik/energieperspektiven-2050-plus.exturl.html/aHR0cHM6Ly9wdWJkYi5iZmUuYWRtaW4uY2gvZGUvcHVibGljYX/Rpb24vZG93bmxvYWQvMTA0MzQ=.html" class="uri">https://www.bfe.admin.ch/bfe/de/home/politik/energieperspektiven-2050-plus.exturl.html/aHR0cHM6Ly9wdWJkYi5iZmUuYWRtaW4uY2gvZGUvcHVibGljYX/Rpb24vZG93bmxvYWQvMTA0MzQ=.html</a>.
</div>
<div id="ref-bracht2025ground" class="csl-entry" role="listitem">
Top Agrar. (2025). <em><span class="nocase">Hessisches Dorf baut riesiges Wasserbecken für eigene Solarthermieanlage</span></em>. <a href="https://www.topagrar.com/energie/news/hessisches-dorf-baut-riesiges-wasserbecken-fur-eigene-solarthermieanlage-20010847.html
" class="uri">https://www.topagrar.com/energie/news/hessisches-dorf-baut-riesiges-wasserbecken-fur-eigene-solarthermieanlage-20010847.html
</a>.
</div>
<div id="ref-tuev2021" class="csl-entry" role="listitem">
TÜV Rheinland. (2021). <em>Annex to solar keymark certificate</em>. <a href="https://www.dincertco.de/logos/011-7S3003%20F.pdf" class="uri">https://www.dincertco.de/logos/011-7S3003%20F.pdf</a>.
</div>
<div id="ref-vauchez2023life" class="csl-entry" role="listitem">
Vauchez, M., Famiglietti, J., Autelitano, K., Colombert, M., Scoccia, R., and Motta, M. (2023). Life cycle assessment of district heating infrastructures: A comparison of pipe typologies in france. <em>Energies</em>, <em>16</em>(9), 3912.
</div>
<div id="ref-vdi2012vdi" class="csl-entry" role="listitem">
VDI, V. (2012). <em><span class="nocase">VDI 2067 Blatt 1" Wirtschaftlichkeit geb<span class="nocase">ä</span>udetechnischer Anlagen-Grundlagen und Kostenberechnung</span></em>. D<span>ü</span>sseldorf.
</div>
<div id="ref-viessmann2021" class="csl-entry" role="listitem">
Viessmann Climate Solutions. (2021). <em><span class="nocase">Großflächen-Solarthermie für die Nah- und Fernwärme</span></em>. <a href="https://energiekonsens.de/media/pages/media/6a0997554c-1640096559/2-viessmann-nah-und-fernwaerme-mit-solarthermie.pdf" class="uri">https://energiekonsens.de/media/pages/media/6a0997554c-1640096559/2-viessmann-nah-und-fernwaerme-mit-solarthermie.pdf</a>.
</div>
<div id="ref-viessmann2024" class="csl-entry" role="listitem">
Viessmann Climate Solutions. (2024). <em><span class="nocase">Energiewende: Solarthermie und Erdspeicher decken rund 70 Prozent des Wärmebedarfs im hessischen Bracht</span></em>. <a href="https://www.viessmann-climatesolutions.com/de/newsroom/unternehmen/erstes-klimaneutrales-mit-solarwaerme-versorgtes-dorf.html" class="uri">https://www.viessmann-climatesolutions.com/de/newsroom/unternehmen/erstes-klimaneutrales-mit-solarwaerme-versorgtes-dorf.html</a>.
</div>
<div id="ref-viessmann2025" class="csl-entry" role="listitem">
Viessmann Climate Solutions. (2025). <em><span class="nocase">Regelungsprogramm für Mittel- und Großkessel</span></em>. <a href="https://www.viessmann.de/de/loesungen/gewerbe-und-industrie/regelung-mittelkessel-grosskessel.html" class="uri">https://www.viessmann.de/de/loesungen/gewerbe-und-industrie/regelung-mittelkessel-grosskessel.html</a>.
</div>
<div id="ref-iea2024" class="csl-entry" role="listitem">
Weiss, W., and Spörk-Dür, M. (2024). <em>Solar heat world wide</em> (White Paper DOI: 10.18777/ieashc-shww-2024-0001). International Energy Agency. <a href="https://www.iea-shc.org/Data/Sites/1/publications/Solar-Heat-Worldwide-2024.pdf">https://www.iea-shc.org/Data/Sites/1/publications/Solar-Heat-Worldwide-2024.pdf</a>
</div>
<div id="ref-werner2017international" class="csl-entry" role="listitem">
Werner, S. (2017). International review of district heating and cooling. <em>Energy</em>, <em>137</em>, 617–631.
</div>
<div id="ref-wernet2016ecoinvent" class="csl-entry" role="listitem">
Wernet, G., Bauer, C., Steubing, B., Reinhard, J., Moreno-Ruiz, E., and Weidema, B. (2016). The ecoinvent database version 3 (part i): Overview and methodology. <em>The International Journal of Life Cycle Assessment</em>, <em>21</em>, 1218–1230.
</div>
<div id="ref-wikipedia2020" class="csl-entry" role="listitem">
Wikipedia. (2025). <em>Solar thermal collector</em>. <a href="https://en.wikipedia.org/wiki/Solar_thermal_collector" class="uri">https://en.wikipedia.org/wiki/Solar_thermal_collector</a>.
</div>
<div id="ref-wolf2017integration" class="csl-entry" role="listitem">
Wolf, S. (2017). <em><span class="nocase">Integration von W<span class="nocase">ä</span>rmepumpen in industrielle Produktionssysteme: Potenziale und Instrumente zur Potenzialerschlie<span class="nocase">ß</span>ung</span></em>.
</div>
<div id="ref-WorldBankWITS2023" class="csl-entry" role="listitem">
World Bank. (2023). <em>Switzerland - electricity imports (product code 271600) in 2023</em>. World Integrated Trade Solution (WITS), World Bank. <a href="https://wits.worldbank.org/trade/comtrade/en/country/CHE/year/2023/tradeflow/Imports/partner/ALL/product/271600">https://wits.worldbank.org/trade/comtrade/en/country/CHE/year/2023/tradeflow/Imports/partner/ALL/product/271600</a>
</div>
<div id="ref-xiang2022comprehensive" class="csl-entry" role="listitem">
Xiang, Y., Xie, Z., Furbo, S., Wang, D., Gao, M., and Fan, J. (2022). A comprehensive review on pit thermal energy storage: Technical elements, numerical approaches and recent applications. <em>Journal of Energy Storage</em>, <em>55</em>, 105716.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This is coincidentally the exact same result as already obtained in <a href="#sec-pipe-loss" class="quarto-xref">Section&nbsp;7.3.1</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>